objectType: docSpace
id: application-examples
version: "1.0.0"
curators:
  - curators@silabs.com
title: "Application Examples"
menu:
  items:
    - docleaf://ae-overview/1.0.0
    - docleaf://ae-getting-started/1.0.0
    - docleaf://ae-application-examples/1.0.0
    - docleaf://ae-sdk-extensions/1.0.0